tradefood/urls.py
from django.urls import path

from . import views

app_name = 'tradefood'
urlpatterns = [
  path('register/', views.register, name='register'),
  # path('register/', views.temp_register_unavailable, name='register-unavail'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout'),
  path('', views.home, name='home'),
  path('offers/', views.open_offers, name='open-offers'),
  path('offers/<int:offer_pk>/', views.offer_details, name='offer-details'),
  path('bid/<int:offer_pk>/', views.submit_bid, name='submit-bid'),
  path('bids/<int:bid_pk>/', views.bid_details, name='bid-details'),
  path('my-offers/', views.my_offers, name='my-offers'),
  path('my-bids/', views.my_bids, name='my-bids'),
  path('trade/', views.submit_offer, name='submit-offer'),
  path('accept-bid/<int:bid_pk>/', views.accept_bid, name='accept-bid'),
  # for let's encrypt
  # path('\.well-known/acme-challenge/Q4uR9oYEZ4l4jFjqhEa_mk6nUkNvtWf2iajClq13GOs/', views.lets_encrypt),
  path('how-it-works/', views.how_it_works, name='how-it-works')
]

twofortwo/urls.py
from django.urls import path, include
from django.contrib import admin

app_name = 'twofortwo'
urlpatterns = [
  path('', include('tradefood.urls')),
  path('admin/', admin.site.urls),
]

tradefood/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from django.utils.timezone import now


class EmailSubscriber(models.Model):
  name = models.CharField(max_length=50)
  email = models.EmailField(max_length=50)

class Merchant(models.Model):
  user = models.OneToOneField(
    User,
    on_delete=models.CASCADE,
    primary_key=True,
  )
  name = models.CharField(max_length=30)
  email = models.EmailField(max_length=50)
  phone = models.CharField(max_length=16)
  street_address = models.CharField(max_length=64)
  zip_code = models.CharField(max_length=5)
  joined = models.DateField(auto_now_add=True)
  verified = models.BooleanField(default=False)

  RESTO = 'RESTAURANT'
  OTHER = 'OTHER'
  CATEGORIES = (
    (RESTO, 'Restaurant'),
    (OTHER, 'Other'),
  )
  category = models.CharField(
    max_length=30,
    choices=CATEGORIES,
    default=RESTO,
  )



class Offer(models.Model):
  description = models.CharField(max_length=256)
  merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE, related_name='offers')
  retail_value = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
  contact_name = models.CharField(max_length=30)
  contact_phone = models.CharField(max_length=16)
  date_posted = models.DateTimeField(auto_now_add=True)
  expiry = models.DateTimeField()
  bid_accepted = models.BooleanField(default=False)
  sms_notifs = models.BooleanField(default=False)

  def is_alive(self):
    time_now = now()
    return self.expiry > time_now and not self.bid_accepted



class Bid(models.Model):
  description = models.CharField(max_length=256)
  merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE, related_name='bids')
  retail_value = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
  contact_name = models.CharField(max_length=30)
  contact_phone = models.CharField(max_length=16)
  offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name='bids')
  # accepted is True when bid is accepted for offer
  accepted = models.BooleanField(default=False)
  date_posted = models.DateTimeField(auto_now_add=True)
  expiry = models.DateTimeField()
  sms_notifs = models.BooleanField(default=False)

  def is_alive(self):
    time_now = now()
    return self.expiry > time_now and not self.accepted

tradefood/forms.py
from django import forms

from tradefood.models import Offer, Bid, Merchant

# class OfferForm(forms.ModelForm):
#   class Meta:
#     model = Offer
#     fields = ['description', 'retail_value', 'contact_name', 'contact_phone', 'duration']
#     localized_fields = ('retail_value',)

# class BidForm(forms.ModelForm):
#   class Meta:
#     model = Bid
#     fields = ['description', 'retail_value', 'contact_name', 'contact_phone', 'duration']
#     localized_fields = ('retail_value',)

DURATION_CHOICES = (
  (0.5, '30 minutes'),
  (1.0, '1 hour'),
  (2.0, '2 hours'),
  (3.0, '3 hours'),
)

class OfferFormCustom(forms.Form):
  description = forms.CharField(max_length=100)
  retail_value = forms.FloatField(required=False, localize=True)
  contact_name = forms.CharField()
  contact_phone = forms.CharField()
  duration = forms.ChoiceField(
    label="Expires in",
    widget=forms.Select,
    choices=DURATION_CHOICES,
  )
  receive_sms_notifications = forms.BooleanField(label="Receive SMS notifications for bids")

class BidFormCustom(forms.Form):
  description = forms.CharField(label="Description", max_length=100)
  retail_value = forms.FloatField(label="Retail value", required=False, localize=True)
  contact_name = forms.CharField(label="Contact name")
  contact_phone = forms.CharField(label="Contact phone")
  duration = forms.ChoiceField(
    label="Expires in",
    widget=forms.Select,
    choices=DURATION_CHOICES,
  )
  receive_sms_notifications = forms.BooleanField(label="Receive SMS notification when bid is accepted")

class EmailSignupForm(forms.Form):
  name = forms.CharField(max_length=50)
  email = forms.EmailField(max_length=50)

class MerchantForm(forms.ModelForm):
  class Meta:
    model = Merchant
    fields = ['name', 'email', 'phone', 'category']

tradefood/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse
from django.urls import reverse

from django.core.exceptions import ObjectDoesNotExist

from django.utils.timezone import timedelta, now

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from tradefood.forms import OfferFormCustom, BidFormCustom, EmailSignupForm
from tradefood.models import Merchant, Offer, Bid, EmailSubscriber
from tradefood.utilities import notify_offerer, notify_bidder

# Create your views here.

@require_http_methods(['GET'])
def lets_encrypt(request):
  return HttpResponse('PkIk0KnC0ebCsF6d4QBaRnFXKstP4t7h7pynlrj860k.LmpInhVWEg6vB1yJk-b8Bd8-yc7wkfxPeiMJwAVbZcQ')

def how_it_works(request):
  return render(request, 'tradefood/info/how_it_works.html')

# Registration temp. unavailable until ready to really launch.
#
@require_http_methods(['GET', 'POST'])
def register(request):
  if request.method == 'POST':
    form_data = request.POST

    # need to validate data before creating
    new_user = User.objects.create_user(
      form_data['username'],
      password=form_data['password'],
    )

    new_merchant = Merchant.objects.create(
      user=new_user,
      name=form_data['name'],
      email=form_data['email'],
      phone=form_data['phone'],
      street_address=form_data['address'],
      zip_code=form_data['zipcode'],
      category=form_data['category'],
    )

    return redirect(reverse('tradefood:login'))

  else:
    return render(request, 'tradefood/auth/register.html')

@require_http_methods(['GET', 'POST'])
def temp_register_unavailable(request):
  if request.method == 'POST':
    form = EmailSignupForm(request.POST)
    if form.is_valid():
      subscriber_info = form.cleaned_data
      subscriber = EmailSubscriber.objects.create(
        name=subscriber_info['name'],
        email=subscriber_info['email']
      )

      # What if they don't enter a name? (Is is required by default?)
      return render(request, 'tradefood/auth/email_signup_success.html', {'name': subscriber_info['name']})
  else:
    form = EmailSignupForm()
    return render(request, 'tradefood/auth/register_unavailable.html', {'form': form})

def login_view(request):
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
      login(request, user)
      return redirect(reverse('tradefood:home'))
    else:
      return render(request, 'tradefood/auth/login.html', {'error_message': 'Invalid login'})

  else:
    return render(request, 'tradefood/auth/login.html')

def logout_view(request):
  logout(request)
  return redirect(reverse('tradefood:home'))

def home(request):
  return render(request, 'tradefood/home.html')

@login_required()
def open_offers(request):
  u = User.objects.get(username=request.user)
  merch = Merchant.objects.get(user=u)
  # offers = Offer.objects.exclude(expiry__lte=now())

  offers = Offer.objects.filter(
    expiry__gt=now(),
    bid_accepted=False
  ).exclude(
    merchant=merch
  )

  return render(request, 'tradefood/offers/offers.html', {'offers': offers})

@login_required()
def submit_bid(request, offer_pk):
  if request.method == 'POST':
    form = BidFormCustom(request.POST)
    if form.is_valid():
      u = User.objects.get(username=request.user)
      merch = Merchant.objects.get(user=u)

      this_offer = Offer.objects.get(pk=offer_pk)

      if this_offer.merchant == merch:
        return render(request, 'tradefood/offer.html', {'error_message': 'Cannot bid on your own order.'})

      form_data = form.cleaned_data
      time_post = now()
      bid_expiry = time_post + timedelta(float(form_data['duration'])/24.0)

      # needed since value can't be null
      rv = form_data['retail_value'] or None

      bid = Bid.objects.create(
        description=form_data['description'],
        merchant=merch,
        offer=this_offer,
        retail_value=rv,
        contact_name=form_data['contact_name'],
        contact_phone=form_data['contact_phone'],
        date_posted=time_post,
        expiry=bid_expiry,
        sms_notifs=form_data['receive_sms_notifications']
      )

      # send SMS notification to offer contact
      if this_offer.sms_notifs: notify_offerer(this_offer)

      return redirect('/my-bids/')
  else:
    this_offer = Offer.objects.get(pk=offer_pk)
    form = BidFormCustom()

    return render(
      request,
      'tradefood/bids/place_bid.html',
      {
       'form': form,
       'offer_pk': offer_pk,
       'description': this_offer.description,
       'merchant': this_offer.merchant.name,
       # 'retail_value': this_offer.retail_value,
       # 'num_bids': this_offer.bids.all().count()
      }
    )

@login_required()
def submit_offer(request):
  if request.method == 'POST':
    form = OfferFormCustom(request.POST)
    if form.is_valid():
      u = User.objects.get(username=request.user)
      merch = Merchant.objects.get(user=u)

      form_data = form.cleaned_data
      time_post = now()
      duration = timedelta(float(form_data['duration'])/24.0)
      offer_expiry = time_post + duration

      # needed since value can't be null
      rv = form_data['retail_value'] or None

      offer = Offer.objects.create(
        description=form_data['description'],
        merchant=merch,
        retail_value=rv,
        contact_name=form_data['contact_name'],
        contact_phone=form_data['contact_phone'],
        date_posted=time_post,
        expiry=offer_expiry,
        sms_notifs=form_data['receive_sms_notifications']
      )

      return redirect('/my-offers/')
  else:
    form = OfferFormCustom()
  return render(request, 'tradefood/offers/trade.html', {'form': form})

@login_required()
def my_bids(request):
  u = User.objects.get(username=request.user)
  merch = Merchant.objects.get(user=u)

  # get bids from today
  bids = merch.bids.filter(
    date_posted__date=now().date()
  ).order_by(
    '-date_posted'
  )

  # e = [is_alive(bid) for bid in bids]
  # alive_bids = [bid for bid in bids if bid.is_alive()]

  # return render(request, 'tradefood/bids/my_bids.html', {'bid_data': zip(bids, e)})
  return render(request, 'tradefood/bids/my_bids.html', {'bids': bids})

@login_required()
def my_offers(request):
  u = User.objects.get(username=request.user)
  merch = Merchant.objects.get(user=u)

  offers = merch.offers.filter(
    date_posted__date=now().date(),
  ).order_by(
    '-date_posted'
  )

  # e = [is_alive(offer) for offer in offers]
  # alive_offers = [offer for offer in offers if offer.is_alive()]

  # return render(request, 'tradefood/bids/my_offers.html', {'offer_data': zip(offers, e)})
  return render(request, 'tradefood/offers/my_offers.html', {'offers': offers})

@login_required()
def bid_details(request, bid_pk):
  u = User.objects.get(username=request.user)
  merch = Merchant.objects.get(user=u)

  bid = Bid.objects.get(pk=bid_pk)

  if bid.offer.merchant == merch:
    return render(request, 'tradefood/bids/bid-offer_owner.html', {'bid': bid, 'owns_offer': True})
  elif bid.merchant == merch:
    return render(request, 'tradefood/bids/bid-bid_owner.html', {'bid': bid, 'owns_bid': True})
  else:
    return render(request, 'tradefood/forbidden.html')

@login_required()
def offer_details(request, offer_pk):
  if request.method == 'GET':
    u = User.objects.get(username=request.user)
    merch = Merchant.objects.get(user=u)

    this_offer = get_object_or_404(Offer, pk=offer_pk)
    try:
      # check whether merch has already bid on this offer
      existing_bid = Bid.objects.get(
        offer=this_offer,
        merchant=merch
      )
    except ObjectDoesNotExist:
      existing_bid = None

    try: 
      winning_bid = this_offer.bids.get(accepted=True)
    except ObjectDoesNotExist:
      winning_bid = None

    payload = {
      'offer': this_offer,
      'winning_bid': winning_bid,
      'existing_bid': existing_bid
    }

    if this_offer.merchant == merch:
      bids = this_offer.bids.all()
      payload['bids'] = bids
      payload['offer_owner'] = True
    else:
      payload['offer_owner'] = False

    return render(request, 'tradefood/offers/offer.html', payload)

@login_required()
def accept_bid(request, bid_pk):
  if request.method == 'POST':
    u = User.objects.get(username=request.user)
    merch = Merchant.objects.get(user=u)

    bid = Bid.objects.get(pk=bid_pk)
    this_offer = bid.offer

    # prevent post requests from other merchants
    if this_offer.merchant != merch:
      return render(request, 'tradefood/forbidden.html')

    if bid.accepted:
      return redirect('/my-offers/', {error_message: 'Bid already accepted.'})

    this_offer.bid_accepted = True
    this_offer.save()

    bid.accepted = True
    bid.save()

    if bid.sms_notifs: notify_bidder(bid)

    return render(
      request,
      'tradefood/bids/bid_accepted.html',
      {
        'offer_desc': this_offer.description,
        'bid_desc': bid.description,
        'bidding_merchant': bid.merchant.name,
        'bid_contact_name': bid.contact_name,
        'bid_contact_phone': bid.contact_phone,
      }
    )

tradefood/templates/tradefood/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% load bootstrap3 %}

  {% load static %}

  {% bootstrap_css %}

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pepperclove</title>

  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Pacifico" rel="stylesheet">
  <link href="{% static 'style.css' %}" rel="stylesheet">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  {% block custom_css %}{% endblock %}
</head>

<body style="padding-top: 50px; padding-bottom: 20px;">
  <nav class="navbar navbar-inverse navbar-fixed-top nav-theme" id="bootstrap-overrides">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" style="font-family: 'Pacifico', cursive;" href="{% url 'tradefood:home' %}">Pepperclove</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="{% if request.resolver_match.url_name == 'tradefood:how-it-works' %}active{% endif %}"><a href="{% url 'tradefood:how-it-works' %}">How it works</a></li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li class="{% if request.resolver_match.url_name == 'tradefood:submit-offer' %}active{% endif %}"><a href="{% url 'tradefood:submit-offer' %}">Post a trade</a></li>
            <li class="{% if request.resolver_match.url_name == 'tradefood:open-offers' %}active{% endif %}"><a href="{% url 'tradefood:open-offers' %}">Open offers</a></li>
            <li class="{% if request.resolver_match.url_name == 'tradefood:my-offers' %}active{% endif %}"><a href="{% url 'tradefood:my-offers' %}">My offers</a></li>
            <li class="{% if request.resolver_match.url_name == 'tradefood:my-bids' %}active{% endif %}"><a href="{% url 'tradefood:my-bids' %}">My bids</a></li>
            <li>{{ user.merchant.name }}</li>
            <li><a href="{% url 'tradefood:logout' %}">Log out</a></li>
          </ul>
        {% else %}
          {% block navbar_right %}
          <form class="navbar-form navbar-right" method="post" action="{% url 'tradefood:login' %}">
            {% csrf_token %}  
            <div class="form-group">
              <input type="text" name="username" placeholder="Username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" name="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
          {% endblock %}
        {% endif %}
      </div><!--/.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <div class="jumbotron">
      {% block error %}
        <p class="lead text-warning-custom">{{ error_message }}</p>
      {% endblock %}
      {% block content %}{% endblock %}
    </div>
  </div>


  <div class="container">
    {% block info %}{% endblock %}  

    <hr>

    <footer>
      <p>&copy; 2017 Pepperclove</p>
    </footer>
  </div> <!-- /container -->

  {% bootstrap_javascript %}
</body>
</html>

tradefood/templates/tradefood/forbidden.html
{% extends "tradefood/base.html" %}

{% block content %}

<h2>You don't have access to this page.</h2>

{% endblock %}

tradefood/templates/tradefood/home.html
{% extends "tradefood/base.html" %}

{% block content %}

<div class="text-center">

  {% if user.is_authenticated %}

    <h1>Pepperclove</h1>

    <h2>Time to get that trade on!</h2>

    <p><a href="{% url 'tradefood:submit-offer' %}">Post</a> something or see what's being <a href="{% url 'tradefood:open-offers' %}"> offered</a>

  {% else %}

    <h1>Pepperclove</h1>

    <h2>where restaurants go to trade food</h2>

    <p class="lead"><a href="{% url 'tradefood:login' %}">Log in</a> or <a href="{% url 'tradefood:register' %}">register</a> to start trading.</p>

  {% endif %}

</div>

{% endblock %}

{% block info %}

  {% if not user.is_authenticated %}
    <div class="row">
      <div class="col-md-4">
        <h2>Enjoy more local food</h2>
        <p>There are so many restaurants around you. Trade with them and get some good food you've never had!</p>
      </div>
      <div class="col-md-4">
        <h2>Share the love</h2>
        <p>Your fellow restaurant industry friends also need good food to eat. Share your greatness by offering something to trade!</p>
     </div>
      <div class="col-md-4">
        <h2>Broaden your horizons</h2>
        <p>Get to know the restaurants around you. The barter economy can really bring a community together!</p>
      </div>
    </div>
  {% else %}

  {% endif %}

{% endblock %}